//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1065 with alias "pageDetails"
	/// <summary>Page Details</summary>
	public partial interface IPageDetails : IPublishedContent
	{
		/// <summary>Description</summary>
		IHtmlString Description { get; }

		/// <summary>Heading</summary>
		string Heading { get; }
	}

	/// <summary>Page Details</summary>
	[PublishedContentModel("pageDetails")]
	public partial class PageDetails : PublishedContentModel, IPageDetails
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageDetails";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageDetails(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageDetails, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static IHtmlString GetDescription(IPageDetails that) { return that.GetPropertyValue<IHtmlString>("description"); }

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("heading")]
		public string Heading
		{
			get { return GetHeading(this); }
		}

		/// <summary>Static getter for Heading</summary>
		public static string GetHeading(IPageDetails that) { return that.GetPropertyValue<string>("heading"); }
	}
}
